# This is a basic workflow to help you get started with Actions

name: scheduled_run

# Controls when the workflow will run
on:
 schedule:
   - cron: 32 16 * * 1-5

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout postman collection files
        uses: actions/checkout@v3

      - name: Install newman
        run: install -g newman

      - name: Run a multi-line script
        run: newman run "C:\Users\Егор\OneDrive\Рабочий стол\Trello_Aleksey.postman_collection.json" -e "C:\Users\Егор\OneDrive\Рабочий стол\Trello_UAT.postman_environment.json" -r htmlextra,cli
          
