# This is a basic workflow to help you get started with Actions

name: scheduled_run

# Controls when the workflow will run
on:
 workflow_dispatch:
 schedule:
   - cron: 00 17 * * 1-5

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install Node on the runner
      - name: Use Node.js  
        uses: actions/setup-node@v1

      # Install newman globally, and install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
        # Run postman collection
      - name: Run Postman Collection and Generate HTML Report
        run: 'newman run Trello.postman_collection.json --reporters cli,htmlextra --reporter-htmlextra-export report.html'
      
      # Make sure that the report has been created
      - name: Chech Files
        run: 'ls' 
        
      # Upload the reports to TestArtifacts directory
      - name: Output the results
        uses: actions/upload-artifact@v3
        with:
         name: Reports
         path: "*html"
          
